apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: splunk-hec
spec:
  port:
    targetPort: 8088 
  tls:
    termination: passthrough
  to:
    kind: Service
    name: splunk-s1-standalone-service
